from __future__ import annotations

import json
import re
import subprocess
import sys
import threading
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from backend import config


_INGESTION_LOCK = threading.Lock()


@dataclass
class IngestionResult:
    filename: str
    stored_path: str
    doc_id: str
    extraction_dir: str


@dataclass
class DocsPdfCandidate:
    filename: str
    doc_id: str
    absolute_path: str
    size_bytes: int
    modified_at: str
    already_indexed: bool


_DOC_ID_CLEAN_RE = re.compile(r"[^A-Za-z0-9._-]+")


def _run_cmd(args: list[str], *, cwd: Path) -> None:
    proc = subprocess.run(args, cwd=str(cwd), capture_output=True, text=True)
    if proc.returncode != 0:
        stderr = (proc.stderr or "").strip()
        stdout = (proc.stdout or "").strip()
        detail = stderr or stdout or "pipeline command failed"
        raise RuntimeError(detail)


def _safe_pdf_filename(name: str) -> str:
    raw = Path(str(name or "document.pdf")).name
    stem = "".join(ch if (ch.isalnum() or ch in ("-", "_", ".")) else "_" for ch in Path(raw).stem)
    stem = stem.strip("._-") or "document"
    return f"{stem}.pdf"


def _doc_id_from_stem(stem: str) -> str:
    return _DOC_ID_CLEAN_RE.sub("_", str(stem or "")).strip("._-").lower() or "document"


def _ensure_unique_path(base_dir: Path, filename: str) -> Path:
    candidate = base_dir / filename
    if not candidate.exists():
        return candidate
    stem = candidate.stem
    suffix = candidate.suffix or ".pdf"
    i = 1
    while True:
        next_candidate = base_dir / f"{stem}_{i}{suffix}"
        if not next_candidate.exists():
            return next_candidate
        i += 1


def _docs_pdf_dir() -> Path:
    docs_dir = config.ROOT_DIR / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    return docs_dir


def _read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _load_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            text = line.strip()
            if not text:
                continue
            rows.append(json.loads(text))
    return rows


def _write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n")


def _replace_doc_rows(existing: list[dict[str, Any]], new_rows: list[dict[str, Any]], doc_id: str) -> list[dict[str, Any]]:
    incoming_chunk_ids = {
        str(row.get("chunk_id") or "").strip()
        for row in new_rows
        if str(row.get("chunk_id") or "").strip()
    }
    kept = [
        row
        for row in existing
        if str(row.get("doc_id") or "").strip().lower() != doc_id.lower()
        and str(row.get("chunk_id") or "").strip() not in incoming_chunk_ids
    ]
    kept.extend(new_rows)
    return kept


def _rebuild_indexes(global_anonymized_path: Path) -> None:
    try:
        _run_cmd(
            [
                sys.executable,
                "scripts/indexing/build_indexes.py",
                "--chunks",
                str(global_anonymized_path),
                "--index-dir",
                "data/indexes",
                "--collection",
                "medical_chunks",
                "--embedding-model",
                "BAAI/bge-m3",
                "--batch-size",
                "2",
                "--reset",
            ],
            cwd=config.ROOT_DIR,
        )
    except RuntimeError as exc:
        report_path = config.ROOT_DIR / "data" / "indexes" / "indexing_report.json"
        try:
            report = _read_json(report_path)
            errors = list(report.get("validation_errors") or [])
        except Exception:
            errors = []
        if errors:
            preview = "; ".join(str(err) for err in errors[:3])
            raise RuntimeError(
                f"Indexation bloquée ({len(errors)} erreurs de validation). Exemples: {preview}"
            ) from exc
        raise


def _process_single_pdf(
    pdf_path: Path,
    *,
    mapping_xlsx_path: Path,
    rebuild_indexes: bool = True,
) -> IngestionResult:
    extraction_root = config.ROOT_DIR / "data" / "extraction"
    temp_root = config.ROOT_DIR / "data" / "tmp_ingestion"
    temp_root.mkdir(parents=True, exist_ok=True)

    _run_cmd(
        [
            sys.executable,
            "scripts/extraction_data/run_extraction.py",
            str(pdf_path),
            "--output-root",
            str(extraction_root),
        ],
        cwd=config.ROOT_DIR,
    )

    # doc_id is generated by extraction from file stem and reflected by output dir.
    # read from the freshest document.json under extraction root matching source pdf.
    latest_doc_json = None
    for candidate in sorted(extraction_root.glob("*/document.json"), key=lambda p: p.stat().st_mtime, reverse=True):
        payload = _read_json(candidate)
        source_pdf = str(payload.get("source_pdf") or "")
        if source_pdf and Path(source_pdf).resolve() == pdf_path.resolve():
            latest_doc_json = candidate
            break
    if latest_doc_json is None:
        raise RuntimeError("Extraction réussie mais document.json introuvable.")

    doc_payload = _read_json(latest_doc_json)
    doc_id = str(doc_payload.get("doc_id") or latest_doc_json.parent.name).strip().lower()
    doc_extraction_dir = latest_doc_json.parent
    doc_temp_raw = temp_root / f"{doc_id}.raw.jsonl"
    doc_temp_anon = temp_root / f"{doc_id}.anonymized.jsonl"
    doc_temp_report = temp_root / f"{doc_id}.anonymization_report.json"

    _run_cmd(
        [
            sys.executable,
            "scripts/chunking/build_chunks.py",
            "--input-root",
            str(doc_extraction_dir),
            "--output",
            str(doc_temp_raw),
            "--report",
            str(temp_root / f"{doc_id}.chunking_report.json"),
        ],
        cwd=config.ROOT_DIR,
    )

    _run_cmd(
        [
            sys.executable,
            "scripts/anonymization/anonymize_chunks.py",
            "--input",
            str(doc_temp_raw),
            "--output",
            str(doc_temp_anon),
            "--mapping-xlsx",
            str(mapping_xlsx_path),
            "--report",
            str(doc_temp_report),
        ],
        cwd=config.ROOT_DIR,
    )

    global_raw = config.ROOT_DIR / "data" / "chunks" / "chunks.raw.jsonl"
    global_anon = config.ROOT_DIR / "data" / "chunks" / "chunks.anonymized.jsonl"
    global_raw.parent.mkdir(parents=True, exist_ok=True)
    global_anon.parent.mkdir(parents=True, exist_ok=True)

    doc_raw_rows = _load_jsonl(doc_temp_raw)
    doc_anon_rows = _load_jsonl(doc_temp_anon)
    existing_raw = _load_jsonl(global_raw)
    existing_anon = _load_jsonl(global_anon)
    _write_jsonl(global_raw, _replace_doc_rows(existing_raw, doc_raw_rows, doc_id))
    _write_jsonl(global_anon, _replace_doc_rows(existing_anon, doc_anon_rows, doc_id))
    if rebuild_indexes:
        _rebuild_indexes(global_anon)

    return IngestionResult(
        filename=pdf_path.name,
        stored_path=str(pdf_path),
        doc_id=doc_id,
        extraction_dir=str(doc_extraction_dir),
    )


def ingest_uploaded_pdfs(files: list[tuple[str, bytes]]) -> list[IngestionResult]:
    if not files:
        return []
    docs_dir = _docs_pdf_dir()
    mapping_xlsx_path = config.ROOT_DIR / "data" / "private" / "anonymization_mapping.xlsx"
    mapping_xlsx_path.parent.mkdir(parents=True, exist_ok=True)

    results: list[IngestionResult] = []
    global_anon = config.ROOT_DIR / "data" / "chunks" / "chunks.anonymized.jsonl"
    with _INGESTION_LOCK:
        for original_name, raw in files:
            safe_name = _safe_pdf_filename(original_name)
            destination = _ensure_unique_path(docs_dir, safe_name)
            destination.write_bytes(raw)
            results.append(_process_single_pdf(destination, mapping_xlsx_path=mapping_xlsx_path, rebuild_indexes=False))
        _rebuild_indexes(global_anon)
    return results


def discover_docs_pdfs(*, indexed_doc_ids: set[str] | None = None) -> list[DocsPdfCandidate]:
    docs_dir = _docs_pdf_dir()
    indexed = {str(value or "").strip().lower() for value in (indexed_doc_ids or set()) if str(value or "").strip()}
    candidates: list[DocsPdfCandidate] = []

    for pdf_path in sorted(docs_dir.glob("*.pdf"), key=lambda p: p.name.lower()):
        try:
            stat = pdf_path.stat()
            size_bytes = int(stat.st_size)
            modified_at = datetime.fromtimestamp(stat.st_mtime, tz=timezone.utc).isoformat()
        except Exception:
            size_bytes = 0
            modified_at = datetime.now(timezone.utc).isoformat()
        doc_id = _doc_id_from_stem(pdf_path.stem)
        candidates.append(
            DocsPdfCandidate(
                filename=pdf_path.name,
                doc_id=doc_id,
                absolute_path=str(pdf_path.resolve()),
                size_bytes=size_bytes,
                modified_at=modified_at,
                already_indexed=doc_id in indexed,
            )
        )
    return candidates


def ingest_docs_by_filenames(filenames: list[str]) -> list[IngestionResult]:
    if not filenames:
        return []
    docs_dir = _docs_pdf_dir()
    mapping_xlsx_path = config.ROOT_DIR / "data" / "private" / "anonymization_mapping.xlsx"
    mapping_xlsx_path.parent.mkdir(parents=True, exist_ok=True)

    safe_names: list[str] = []
    for raw_name in filenames:
        name = Path(str(raw_name or "")).name
        if not name or not name.lower().endswith(".pdf"):
            continue
        safe_names.append(name)
    if not safe_names:
        raise RuntimeError("Aucun nom de fichier PDF valide.")

    unique_names = sorted(set(safe_names))
    results: list[IngestionResult] = []
    global_anon = config.ROOT_DIR / "data" / "chunks" / "chunks.anonymized.jsonl"

    with _INGESTION_LOCK:
        for name in unique_names:
            pdf_path = (docs_dir / name).resolve()
            if not pdf_path.exists() or not pdf_path.is_file():
                raise RuntimeError(f"Fichier introuvable dans docs/: {name}")
            try:
                pdf_path.relative_to(docs_dir.resolve())
            except Exception as exc:
                raise RuntimeError(f"Chemin invalide: {name}") from exc
            results.append(_process_single_pdf(pdf_path, mapping_xlsx_path=mapping_xlsx_path, rebuild_indexes=False))
        _rebuild_indexes(global_anon)

    return results


def reindex_single_doc(doc_id: str, source_pdf_path: Path) -> IngestionResult:
    mapping_xlsx_path = config.ROOT_DIR / "data" / "private" / "anonymization_mapping.xlsx"
    mapping_xlsx_path.parent.mkdir(parents=True, exist_ok=True)
    with _INGESTION_LOCK:
        return _process_single_pdf(source_pdf_path, mapping_xlsx_path=mapping_xlsx_path)
