from __future__ import annotations

# Extensible analyte alias groups (canonical analyte_norm -> aliases).
# Keep this list as a complement to dynamic analytes loaded from structured data.
ANALYTE_ALIAS_GROUPS: dict[str, list[str]] = {
    "calcitonine": ["calcitonine"],
    "procalcitonine": ["procalcitonine"],
    "ferritine": ["ferritine"],
    "lithium": ["lithium"],
    "c3": ["c3", "complement c3", "complément c3"],
    "c4": ["c4", "complement c4", "complément c4"],
    "cholesterol_hdl": ["hdl", "cholesterol hdl", "cholestérol hdl", "cholesterol_hdl"],
    "cholesterol_total": [
        "cholesterol total",
        "cholestérol total",
        "cholesterol_total",
        "chol total",
        "cholest total",
    ],
    "acide_urique": ["acide urique", "acide_urique", "uric acid", "urate", "uricemie", "uricémie"],
    "crp": ["crp", "proteine c reactive", "protéine c réactive", "protein c reactive"],
    "peptide_c": ["peptide c", "peptide_c", "peptide-c"],
    "insuline": ["insuline"],
    "pro_bnp": ["pro bnp", "pro_bnp", "pro-bnp", "probnp"],
    "tshus": [
        "tshus",
        "tsh us",
        "tsh-us",
        "tsh ultra sensible",
        "tsh ultra-sensible",
        "tsh ultrasensible",
        "tsh",
    ],
    "tsh": ["tsh", "thyreostimuline", "thyréostimuline", "thyroid stimulating hormone"],
    "acth": ["acth"],
    "troponine": ["troponine", "troponine i", "troponine t"],
    "ace": ["ace"],
    "psa_totale": ["psa totale", "psa total", "psa"],
    "ca_15_3": ["ca 15-3", "ca 15 3", "ca15-3", "ca153"],
    "t4_libre": ["t4 libre", "t4l", "ft4", "t4", "thyroxine libre", "free t4", "t4libre"],
    "t3_libre": ["t3 libre", "t3l", "ft3", "t3", "triiodothyronine libre", "free t3", "t3libre"],
    "anti_tg": ["anti tg", "anti-tg", "anti thyroglobuline", "anticorps anti tg", "anti tg antibodies"],
    "ckmb": ["ckmb", "ck mb", "ck-mb", "cpkmb", "cpk mb", "cpk-mb", "ckmb (cpkmb)"],
    "ldh": ["ldh", "ldh total", "lactate dehydrogenase", "lactate deshydrogenase", "lactate déshydrogénase"],
    "bilirubine_directe": [
        "bilirubine directe",
        "bilirubine_directe",
        "bilirubine conjuguée",
        "bilirubine conjuguee",
        "direct bilirubin",
        "bilirubin direct",
    ],
    "ammonium": ["ammonium", "ion ammonium", "nh4", "nh4+", "ammoniac"],
    "apo_a1": ["apo a1", "apoa1", "apolipoprotéine a1", "apolipoproteine a1", "apolipoproteine-a1"],
    "triglycerides": ["triglycerides", "triglycérides"],
    "cholesterol_ldl": ["ldl", "cholesterol ldl", "cholestérol ldl", "cholesterol ldl-c", "ldl c"],
    "microalbuminurie": ["microalbuminurie", "micro albuminurie", "microalbumine"],
    "ethanol": ["ethanol", "éthanol", "alcool", "ethyl"],
    "acide_valproique": [
        "acide valproique",
        "acide valproïque",
        "acide valporoique",
        "valproate",
        "valproique",
        "valporoique",
        "depakine",
        "depakine chrono",
    ],
    "carbamazepine": ["carbamazepine", "carbamazépine"],
    "calcium": ["calcium"],
    "creatinine": [
        "creatinine",
        "créatinine",
        "creatine",
        "créatine",
        "creat",
        "créat",
        "creatininemie",
        "créatininémie",
        "CREATININE",
        "CRÉATININE",
    ],
    "amh": ["amh", "hormone anti mullerienne", "hormone anti müllerienne", "anti mullerienne"],
    "pth_intact": ["pth intacte", "pth intact", "parathormone intacte", "parathormone", "pthi", "pth"],
    "vitamine_b12": ["vitamine b12", "vitamine_b12", "vit b12", "b12"],
    "vitamine_d": ["vitamine d", "vitamine_d", "25 oh vitamine d", "25-oh vitamine d"],
    "trichuris": ["trichuris", "trichuris trichiura"],
    "ankylostoma": ["ankylostoma"],
    "haptoglobine": ["haptoglobine"],
    "phosphatase_alcaline": [
        "phosphatase alcaline",
        "phosphatases alcalines",
        "pal",
        "alp",
        "alkaline phosphatase",
    ],
    "amphetamine": ["amphétamine", "amphetamine", "amphetamines", "amphétamines"],
    "benzodiazepine": ["benzodiazépine", "benzodiazepine", "benzodiazépines", "benzodiazepines"],
    "cocaine": ["cocaine", "cocaïne"],
    "ecstasy": ["ecstasy", "mdma"],
    "opiaces": ["opiaces", "opiacés", "opiacé", "opiace"],
    "phencyclidine": ["phencyclidine", "pcp"],
    "gh_ou_sth": ["gh", "sth", "gh ou sth"],
    "glucose": ["glucose", "glycemie", "glycémie", "glycemie a jeun", "glycémie à jeun", "glucose sanguin"],
    "cortisol": ["cortisol", "cortisolemie", "cortisolémie", "cortisol sanguin"],
}
